backend:
  name: git-gateway
  branch: main

media_folder: public/images
public_folder: /images

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
      - { label: "Project Link", name: "link", widget: "string", required: false }
      - { label: "Cover Image", name: "image", widget: "image", required: false }
      - { label: "Date", name: "date", widget: "string", required: false }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Details (optional)", name: "body", widget: "markdown", required: false }
